### ISSUE TITLE
The redligning labels isn't refresh when the language changed

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#1556]

**Comment by sbrunner** [comment]
fixed with #1555

**Comment by olivierSemet** [comment]
@pgiraud @sbrunner this issue is not fully fixed. The issue #1576 is directly linked to it

**Comment by sbrunner** [comment]
For me it can be closed, #1576 has every informations...
